### PR TITLE
Add missing colors and some fixes

### PR DESCRIPTION
**Pull request by ZorinFoss**

### CODE REVIEW

**Comment by MordFustang21** [comment]
These changes seem to be overriding all the colors and making it no longer match the original port. 
image

**Comment by ZorinFoss** [comment]
The background colors can be changes to match the original one.

**Comment by ZorinFoss** [comment]
i fix the background to match the original one.

**Comment by ZorinFoss** [comment]
Now it almost identical with the original.

**Comment by MordFustang21** [comment]
I don't feel comfortable merging this due to the large amount of changes. If it was a couple small fixes to correct symbol highlighting etc that would be great. However this appears to be changing all the colors and they don't seem to even match the ones from the original.

**Pull request closed without merging**
